#!/usr/bin/env python3
"""Assemble the news grid in index.html from one folder per news item.

Layout expected next to this script:

    news/
      2026-09-19_lab-outing/
        news.html      # the card's inner block (<a ...> or <div ...> ... )
        MiBarrio.jpg   # image referenced by bare filename inside news.html
      2026-03-30_embs-webinar/
        ...
    index.html         # contains the NEWS:START / NEWS:END markers

Each folder name must start with an ISO date (YYYY-MM-DD) followed by "_"
and a short slug. Folders are sorted newest first by that name. Inside
news.html any bare `src="file"` is rewritten to `src="news/<folder>/file"`
so the fragment can stay self-contained.

Usage:
    python3 build_news.py          # rewrite index.html in place
    python3 build_news.py --check  # exit 1 if index.html is out of date
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

# Everything is resolved relative to this file, so the script works no
# matter which directory it is invoked from.
ROOT = Path(__file__).resolve().parent
NEWS_DIR = ROOT / "news"
INDEX = ROOT / "index.html"
FRAGMENT_NAME = "news.html"

START_MARK = "<!-- NEWS:START (generated by build_news.py, do not edit by hand) -->"
END_MARK = "<!-- NEWS:END -->"

# Folder names must look like 2026-09-19_some-slug
FOLDER_RE = re.compile(r"^\d{4}-\d{2}-\d{2}_.+")
# A bare filename in src="..." (no slash, no scheme). Group 1 keeps the quote.
BARE_SRC_RE = re.compile(r'src=(["\'])(?![^"\']*[/:])([^"\']+)\1')

# The grid lives five tab-stops deep in index.html; cards get one more.
GRID_INDENT = "\t" * 5
CARD_INDENT = "\t" * 6
INNER_INDENT = "\t" * 7


def load_fragment(folder: Path) -> str | None:
    """Read news.html from a folder and fix its image paths.

    Returns the fragment text, or None (after printing a warning) if the
    folder is unusable so the build can carry on with the other items.
    """
    fragment_file = folder / FRAGMENT_NAME
    if not fragment_file.is_file():
        print(f"warning: {folder.name}: no {FRAGMENT_NAME}, skipped", file=sys.stderr)
        return None

    text = fragment_file.read_text(encoding="utf-8").strip()

    # Check every referenced image actually exists before rewriting the path.
    missing = [
        name for _, name in BARE_SRC_RE.findall(text) if not (folder / name).is_file()
    ]
    if missing:
        print(
            f"warning: {folder.name}: missing image(s) {missing}, skipped",
            file=sys.stderr,
        )
        return None

    # "src="EMM.png"" -> "src="news/2025-09-24_ensemble/EMM.png""
    return BARE_SRC_RE.sub(
        lambda m: f"src={m.group(1)}news/{folder.name}/{m.group(2)}{m.group(1)}", text
    )


def format_date(folder_name: str) -> str:
    """Turn the leading YYYY-MM-DD of a folder name into a short label, e.g. '25 Mar 2026'."""
    day = date.fromisoformat(folder_name[:10])
    return f"{day.day} {day.strftime('%b %Y')}"


def add_date(fragment: str, label: str) -> str:
    """Insert a <span class="news-date"> just before the card's <h3> title.

    The fragment author never writes the date by hand; it always comes from the
    folder name, so renaming the folder is the only way to change it.
    """
    span = f'<span class="news-date">{label}</span>'
    if "<h3" in fragment:
        return fragment.replace("<h3", f"{span}\n    <h3", 1)
    return fragment  # no title: leave the fragment untouched


def render_card(fragment: str) -> str:
    """Wrap a fragment in the column div and indent it like index.html.

    Fragments are written with two-space indentation; each level becomes one
    tab on top of the base indent so the output matches the rest of the file.
    """
    inner_lines = []
    for line in fragment.splitlines():
        stripped = line.lstrip(" \t")
        if not stripped:
            continue  # drop blank lines inside the fragment
        leading = line[: len(line) - len(stripped)]
        # Two spaces or one tab in the fragment == one extra tab in index.html.
        depth = leading.count("\t") + leading.count(" ") // 2
        inner_lines.append(INNER_INDENT + "\t" * depth + stripped.rstrip())
    inner = "\n".join(inner_lines)
    return (
        f'{CARD_INDENT}<div class="col-4 col-12-medium">\n'
        f"{inner}\n"
        f"{CARD_INDENT}</div>"
    )


def build_grid() -> str:
    """Collect all news folders, newest first, and render them as one block."""
    if not NEWS_DIR.is_dir():
        sys.exit(f"error: {NEWS_DIR} does not exist")

    folders = sorted(
        (p for p in NEWS_DIR.iterdir() if p.is_dir() and FOLDER_RE.match(p.name)),
        key=lambda p: p.name,
        reverse=True,  # ISO dates sort correctly as plain text
    )

    cards = []
    for folder in folders:
        fragment = load_fragment(folder)
        if fragment is not None:
            cards.append(render_card(add_date(fragment, format_date(folder.name))))

    print(f"{len(cards)} news item(s) rendered", file=sys.stderr)
    return "\n\n".join(cards)


def splice(html: str, grid: str) -> str:
    """Replace whatever sits between the markers with the freshly built grid."""
    start = html.find(START_MARK)
    end = html.find(END_MARK)
    if start == -1 or end == -1 or end < start:
        sys.exit(f"error: markers not found in {INDEX.name}; add\n"
                 f"  {START_MARK}\n  {END_MARK}\ninside the news row")

    before = html[: start + len(START_MARK)]
    after = html[end:]
    return f"{before}\n{grid}\n{GRID_INDENT}{after}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if index.html would change",
    )
    args = parser.parse_args()

    original = INDEX.read_text(encoding="utf-8")
    updated = splice(original, build_grid())

    if updated == original:
        print(f"{INDEX.name} is up to date", file=sys.stderr)
        return

    if args.check:
        sys.exit(f"{INDEX.name} is out of date; run: python3 {Path(__file__).name}")

    INDEX.write_text(updated, encoding="utf-8")
    print(f"{INDEX.name} updated", file=sys.stderr)


if __name__ == "__main__":
    main()
